### ISSUE TITLE
有关ibuprofen使用方法

### ISSUE THREAD

**Issue by zycn0910** [Richard-Zheng/ibuprofen#1]
你好，在使用此项目进行少年派自主学习文件抓取后，效果十分 _**显著**_ 。但是随着使用的不断深入，一些问题也接踵而来。阅读README.MD介绍时只知道能抓取自主学习的数据，但在查看项目代码后发现还有上传文件的功能，功能代码完备，于是我对workflow代码进行了及其细小的改动。运行后并未发现上传功能的使用方法，而且site文件夹中的html单页在runflow后也无法找到，针对我遇到的这些问题，希望能有一份详尽的项目的正确使用方法。

**Comment by Richard-Zheng** [comment]
workflow 仅抓取自主学习的数据并生成 HTML 直接上传。其他的 Python 脚本需要 clone 到装有 Python 的本地设备上运行，请你自己查询 Python 安装方法。

如果不知道怎么调用某个文件的话请在 Terminal 执行 `python {filename} -h` （替换{filename}为 Python 脚本文件名）查看文档，或者你也可以自学 [argparse 模块](https://docs.python.org/zh-cn/3/library/argparse.html) 的使用方法并对照源码反推命令行接口。

如果没有额外问题的话请自行 close issue.
