### ISSUE TITLE
使用Action可能出现的隐私泄露

### ISSUE THREAD

**Issue by Wtrwx** [Richard-Zheng/ibuprofen#3]

**Comment by Richard-Zheng** [comment]
好的，一会加上

另外对于生成出来的静态网页，其实能自动托管是最方便的。

目前有两个方案

1. 自动push到GitHub Pages（仍然无法解决隐私泄露问题）
2. 上传到某个对象存储（难度高，隐私性好）
   甚至可以传到学校服务器（

**Comment by Richard-Zheng** [comment]
还有一个看起来像是补丁的方案，即加一个参数让用户输入密码，用于加密打包zip包。

我没什么时间写。如果有人愿意试试，欢迎Fork和PR。

**Comment by Richard-Zheng** [comment]
solved 955dd6b
